# coding: utf-8
"""Waylay Function Registry.

V2 API to build and deploy Waylay functions (plugs, webscripts, BYOML models).

The version of the OpenAPI document: 2.11.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""  # noqa: E501

from waylay.config import WaylayConfig
from waylay.__version__ import __version__


class ApiConfig:
    """API client settings."""

    def __init__(self, waylay_config: WaylayConfig, _client_options=None) -> None:
        """Create an instance."""
        self.waylay_config = waylay_config
        """Waylay configuration."""
        self._client_options = _client_options
        """Additional REST client options."""

        self.datetime_format = "%Y-%m-%dT%H:%M:%S.%f%z"
        """Datetime format."""

        self.date_format = "%Y-%m-%d"
        """Date format."""

    @property
    def host(self):
        """Return generated host."""
        return self.waylay_config.gateway_url

    @property
    def client_side_validation(self):
        """Return whether client side validation is enabled or not."""
        return self.waylay_config.client_side_validation
